# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "ivanovaa1992@gmail.com",
  "firstname": "sasha",
  "lastname": "ivanov",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/7aef6925-4fe5-4057-b5cc-cc7cf214df05 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "654321"
}

###

# Get new JWT pair
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODVhYzlmOTIzN2ZkMGU1N2M3OTRlZjUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTc1MDc4MjI2OSwiZXhwIjoxNzUwNzgyNTY5fQ.PsVUVv2z6hB9j3xMtq1S6LNVYOGXouwzUOpb5m1kKzg

###

# Check token
POST http://localhost:3000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODVhYzlmOTIzN2ZkMGU1N2M3OTRlZjUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTc1MDc4MjE4NCwiZXhwIjoxNzUwNzgyNDg0fQ.WpRGnDcmhzTHmtUPpgorB-NNl5t-a3pRTUunKUq2hsU

###

# Change user password
POST http://localhost:3000/api/auth/change-password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODVhYzlmOTIzN2ZkMGU1N2M3OTRlZjUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTc1MDc4MjE4NCwiZXhwIjoxNzUwNzgyNDg0fQ.WpRGnDcmhzTHmtUPpgorB-NNl5t-a3pRTUunKUq2hsU
Content-Type: application/json

{
  "oldPassword": "123456",
  "newPassword": "654321"
}

###
