# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "ivanovaa1994@gmail.com",
  "firstname": "sasha5",
  "lastname": "ivanov5",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/685adcb1154ef53d878a7268 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "ivanovaa1993@gmail.com",
  "password": "123456"
}

###

# Toggle subscribe
POST http://localhost:3000/api/auth/toggle-subscribe HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODViMzcyNDgzYTRjY2Y0ZjM3MDc4YmYiLCJlbWFpbCI6Iml2YW5vdmFhMTk5M0BnbWFpbC5jb20iLCJsYXN0bmFtZSI6Iml2YW5vdjIyIiwiZmlyc3RuYW1lIjoic2FzaGEyMiIsImlhdCI6MTc1MDgwOTk4NCwiZXhwIjoxNzUwODEwMjg0fQ.rToou2bouFK8R-aGe92TvtPc9_mEd_qsv6LiIthNEiI
Content-Type: application/json

{
  "publisherId": "685adcb1154ef53d878a7268"

}
###
# Get new JWT pair
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODVhYzlmOTIzN2ZkMGU1N2M3OTRlZjUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTc1MDc4MjI2OSwiZXhwIjoxNzUwNzgyNTY5fQ.PsVUVv2z6hB9j3xMtq1S6LNVYOGXouwzUOpb5m1kKzg

###

# Check token
POST http://localhost:3000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODVhYzlmOTIzN2ZkMGU1N2M3OTRlZjUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTc1MDc4MjE4NCwiZXhwIjoxNzUwNzgyNDg0fQ.WpRGnDcmhzTHmtUPpgorB-NNl5t-a3pRTUunKUq2hsU

###

# Change user password
POST http://localhost:3000/api/auth/change-password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODVhYzlmOTIzN2ZkMGU1N2M3OTRlZjUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTc1MDc4MjE4NCwiZXhwIjoxNzUwNzgyNDg0fQ.WpRGnDcmhzTHmtUPpgorB-NNl5t-a3pRTUunKUq2hsU
Content-Type: application/json

{
  "oldPassword": "123456",
  "newPassword": "654321"
}

###

# Create a new post
POST http://localhost:3000/api/blog/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODViMzcyNDgzYTRjY2Y0ZjM3MDc4YmYiLCJlbWFpbCI6Iml2YW5vdmFhMTk5M0BnbWFpbC5jb20iLCJsYXN0bmFtZSI6Iml2YW5vdjIyIiwiZmlyc3RuYW1lIjoic2FzaGEyMiIsImlhdCI6MTc1MDgxMzcyNCwiZXhwIjoxNzUwODE0MDI0fQ.Yf3ciYsCL4130GTif_CJtxcAF4Tfet3qW3aHT4i7GsQ
Content-Type: application/json

{
  "type": "text",
  "status": "draft",
  "content": { "title": "My first post!", "announcement": "My first post!", "content": "My first post!" },
  "tags": ["tag1", "tag2"],
  "isRepost": false
}

###

# Update a post
POST http://localhost:3000/api/blog/update HTTP/1.1
Authorization: Bearer <your_jwt_token>
Content-Type: application/json

{
  "id": "123e4567-e89b-12d3-a456-426614174000",
  "type": "Text",
  "status": "Draft",
  "content": { "text": "Updated post content" },
  "tags": ["tag1", "tag2"],
  "isRepost": false,
  "createdAt": "2024-03-20T12:00:00Z"
}

###

# Get all posts
GET http://localhost:3000/api/blog/?page=1&limit=10 HTTP/1.1

###

# Get subscribed posts
GET http://localhost:3000/api/blog/subscriptions?page=1&limit=10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODViMzcyNDgzYTRjY2Y0ZjM3MDc4YmYiLCJlbWFpbCI6Iml2YW5vdmFhMTk5M0BnbWFpbC5jb20iLCJsYXN0bmFtZSI6Iml2YW5vdjIyIiwiZmlyc3RuYW1lIjoic2FzaGEyMiIsImlhdCI6MTc1MDgwOTk4NCwiZXhwIjoxNzUwODEwMjg0fQ.rToou2bouFK8R-aGe92TvtPc9_mEd_qsv6LiIthNEiI
###

# Get post by id
GET http://localhost:3000/api/blog/123e4567-e89b-12d3-a456-426614174000 HTTP/1.1

###

# Delete post
POST http://localhost:3000/api/blog/delete/123e4567-e89b-12d3-a456-426614174000 HTTP/1.1
Authorization: Bearer <your_jwt_token>

###

# Repost a post
POST http://localhost:3000/api/blog/98159a90-a27a-4826-8f72-efb747a3a83e/repost HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODVhZGNiMTE1NGVmNTNkODc4YTcyNjgiLCJlbWFpbCI6Iml2YW5vdmFhMTk5MkBnbWFpbC5jb20iLCJsYXN0bmFtZSI6Iml2YW5vdiIsImZpcnN0bmFtZSI6InNhc2hhIiwiaWF0IjoxNzUwODA2MTk1LCJleHAiOjE3NTA4MDY0OTV9.fS2CetMDEeTbqFrVNHVTtaOY-ieHYS3Yh07rIx00VZg
Content-Type: application/application/json

###

# Create a comment for a post
POST http://localhost:3000/api/blog/123e4567-e89b-12d3-a456-426614174000/comments/create HTTP/1.1
Authorization: Bearer <your_jwt_token>
Content-Type: application/json

{
  "content": "This is a test comment for the post.",
  "postId": "123e4567-e89b-12d3-a456-426614174000"
}

###

# Get all comments for a post
GET http://localhost:3000/api/blog/123e4567-e89b-12d3-a456-426614174000/comments?page=1&limit=10 HTTP/1.1

###

# Get a comment by id for a post
GET http://localhost:3000/api/blog/123e4567-e89b-12d3-a456-426614174000/comments/987e6543-e21b-12d3-a456-426614174999 HTTP/1.1

###

# Create a like for a post
POST http://localhost:3000/api/blog/98159a90-a27a-4826-8f72-efb747a3a83e/likes/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODVhZGNiMTE1NGVmNTNkODc4YTcyNjgiLCJlbWFpbCI6Iml2YW5vdmFhMTk5MkBnbWFpbC5jb20iLCJsYXN0bmFtZSI6Iml2YW5vdiIsImZpcnN0bmFtZSI6InNhc2hhIiwiaWF0IjoxNzUwODA0MDI1LCJleHAiOjE3NTA4MDQzMjV9.Xg-o_bWY3zzIFoxFAbmJTuA9tUf-JdALKcBhyvu63M0
Content-Type: application/json

###

# Delete a like for a post
DELETE http://localhost:3000/api/blog/98159a90-a27a-4826-8f72-efb747a3a83e/likes/delete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODVhZGNiMTE1NGVmNTNkODc4YTcyNjgiLCJlbWFpbCI6Iml2YW5vdmFhMTk5MkBnbWFpbC5jb20iLCJsYXN0bmFtZSI6Iml2YW5vdiIsImZpcnN0bmFtZSI6InNhc2hhIiwiaWF0IjoxNzUwODA0MDI1LCJleHAiOjE3NTA4MDQzMjV9.Xg-o_bWY3zzIFoxFAbmJTuA9tUf-JdALKcBhyvu63M0
Content-Type: application/json


###